export const mock_card = {
  alignment: "",
  logo: "",
  enableLogo: true,
  frontText: "",
  enableFrontText: true,
  backText: "",
  backgroundColor: "",
  backgroundImage: "",
  fontFamily: "",
};

export const card_preset = [
  {
    alignment: "",
    logo: "",
    enableLogo: true,
    frontText: "",
    enableFrontText: true,
    backText: "",
    backgroundColor: "",
    backgroundImage: "",
    fontFamily: "",
    selected: false,
  },
  {
    alignment: "start",
    logo: "",
    enableLogo: true,
    frontText: "",
    enableFrontText: true,
    backText: "",
    backgroundColor: "linear-gradient(270deg, #E63946 0.11%, #1D3557 99.89%)",
    backgroundImage: null,
    fontFamily: "Trebuchet MS",
    selected: false,
  },
  {
    alignment: "center",
    logo: "",
    enableLogo: true,
    frontText: "Bussiness Card",
    enableFrontText: true,
    backText: "",
    backgroundColor: "linear-gradient(270deg, #FAA307 0.11%, #9D0208 99.89%)",
    backgroundImage: null,
    fontFamily: "Arial",
    selected: false,
  },
];
